### ISSUE TITLE
其中的mqtt好像没有自动重连功能？

### ISSUE THREAD

**Issue by skyformat99** [zhaojh329/evmongoose#1]
如题？
这个可以解决嚒？
比如，作为client连接到broker时，如果网络断了，或者broker重启的时候，
如何自动重连，并且继续发送数据，订阅数据呢？
谢谢

**Comment by zhaojh329** [comment]
有自动重连的，你看下example里面的mqtt例子就明白了

**Comment by skyformat99** [comment]
大牛牛，请教一下，原作者自定义的ev和这个用的libev，
效果应该差不多吧？
有什么区别？

**Comment by zhaojh329** [comment]
不同的概念

**Comment by skyformat99** [comment]
在这个地方试着加了自动重连的代码：mqtt_client.c
case MG_EV_CLOSE:
   printf("Connection closed\n");

还是没有成功。。能帮忙添加一个嘛？

**Comment by zhaojh329** [comment]
刚刚已经添加

**Comment by skyformat99** [comment]
例子测试了一下，有问题。

现象：过一段时间client自己断开，然后又重连的。
这个应该不对，应该发送ping指令。

断开重连，应该是被动断开的情况下（比如网络故障、broker故障），自动重连。

**Comment by zhaojh329** [comment]
一旦连接成功，库里面会周期性发送ping包

**Comment by skyformat99** [comment]
道理是这样。
但是实际效果是，先断开，然后再连接上的。
因为这个时候其实是正常连接的。

**Comment by zhaojh329** [comment]
加qq群讨论吧

**Comment by zhaojh329** [comment]
已经修复
